# Generated by Django 4.2.7 on 2026-06-18 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voting", "0002_poll_reject_reason_poll_reviewed_at_poll_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "poll", "option")},
        ),
        migrations.AddField(
            model_name="vote",
            name="single_vote_key",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "single_vote_key"), ("user", "poll", "option")},
        ),
    ]
